### ISSUE TITLE
UDF support disabled

### ISSUE THREAD

**Issue by jag-chaudhari** [borisbrodski/sevenzipjbinding#16]
Hi
Can you enable UDF support in the java library?

My existing code supports UDF data processing but when I upgrade 7z libs to 16.02, it just doesn't compile.

If you could build libs with UDF support enabled and share them with me, that would be great.

Thank you

**Comment by borisbrodski** [comment]
Hi,

UDF was temporary removed due to security reasons. See this commit for more information:
https://github.com/borisbrodski/sevenzipjbinding/commit/86d29e955dcf8d15acf7180232f1556deb759c53

But you could clone the git repository, revert this commit and build 7-Zip-JBinding yourself (and for your own risk).

Since the security problems were fixed in the 7-Zip, I will enable UDF and other affected formats while migrating to the next version.

**Comment by jag-chaudhari** [comment]
Sounds good, thanks!

**Comment by david-sitsky** [comment]
Any ideas on when the new version will be released?  I'd like to see UDF support re-enabled again.  Many thanks.

**Comment by borisbrodski** [comment]
Version 16.02 (with non-beta release) has the UDF support enabled again. It will be released on 19.02.2020.
