### ISSUE TITLE
[JAVA] how to compress many big files at once  ,such as 30 files , every file size is 500MB

### ISSUE THREAD

**Issue by wshidaijingshen** [borisbrodski/sevenzipjbinding#32]
such as there're 30 files ,and  each file size is 500MB.
As we all know memory is very important for jvm , Is JVM  able to do this job ? 
If there anyone has test this ,please share your idea about this   very much thx .

**Comment by borisbrodski** [comment]
Hello @wshidaijingshen 

Sure. 7-Zip-JBinding can easily do this.

You have to stream your data and never load it in a byte[] array at ones.
Instead of using ByteArrayStream from the [examples](http://sevenzipjbind.sourceforge.net/compression_snippets.html) you have to use [RandomAccessFileInStream](http://sevenzipjbind.sourceforge.net/javadoc/net/sf/sevenzipjbinding/impl/RandomAccessFileInStream.html) to read your files or implement the [ISequentialInStream](http://sevenzipjbind.sourceforge.net/javadoc/net/sf/sevenzipjbinding/ISequentialInStream.html) yourself if your data comes from some custom source.

**Comment by wshidaijingshen** [comment]
thx for answer, I'll try it 

> Hello @wshidaijingshen
> 
> Sure. 7-Zip-JBinding can easily do this.
> 
> You have to stream your data and never load it in a byte[] array at ones.
> Instead of using ByteArrayStream from the [examples](http://sevenzipjbind.sourceforge.net/compression_snippets.html) you have to use [RandomAccessFileInStream](http://sevenzipjbind.sourceforge.net/javadoc/net/sf/sevenzipjbinding/impl/RandomAccessFileInStream.html) to read your files or implement the [ISequentialInStream](http://sevenzipjbind.sourceforge.net/javadoc/net/sf/sevenzipjbinding/ISequentialInStream.html) yourself if your data comes from some custom source.

Thx for your answer, I'll try it

**Comment by wshidaijingshen** [comment]
After using RandomAccessFileInStream  instead of ByteArrayStream , one should always remember to close the it.
If not ,you'll fail to delete old files after the compression done.
It cost me much time to find out how to delete the old files, and turns out it's just such a small thing to do. OMG. Almost kill me.
Here is the simple code you should pay attention :

![image](https://user-images.githubusercontent.com/34682234/94361882-0e779f80-00ea-11eb-855e-d6f4c47bb581.png)

**Comment by borisbrodski** [comment]
Thank you for the nice explanation. Depending on the number of the files you compressing and operating system, it may be a good idea to not close all the files on the end, but rather when they are not needed any more. It's bit tricky and will definitely  add more tools to support it.

I also plan to add a working example to the home page.
